stockbot/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from stocks.views import IndexView

# ----------------------------------------------------------------------------------------


urlpatterns = [

	url(r'^$', IndexView.as_view(), name='index'),
    url(r'^databases/', include('databases.urls', namespace='databases')),
    url(r'^datasets/', include('datasets.urls', namespace='datasets')),
    url(r'^admin/', admin.site.urls),

]

stockbot/databases/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^$', views.DatabasesView.as_view(), name='list'),
	url(r'^(?P<page>[\d]+)/$', views.DatabasesView.as_view(), name='list'),
	
	url(r'^download/(?P<database_code>[\w]+)/$', views.DownloadDatabaseView.as_view(), name='download'),
	
]

# ----------------------------------------------------------------------------------------

stockbot/datasets/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^$', views.DatasetsView.as_view(), name='list'),
	url(r'^(?P<page>[\d]+)/$', views.DatasetsView.as_view(), name='list'),
	
]

# ----------------------------------------------------------------------------------------

stockbot/databases/models.py
from django.db import models

# Create your models here.

stockbot/datasets/models.py
from django.db import models

# Create your models here.

stockbot/stocks/models.py
from django.db import models

# Create your models here.

stockbot/databases/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals
import re

# Core django imports
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View

# Thrid party app imports

# Project imports
from stockbot.quandl_api import DatabaseAPI

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

database_api = DatabaseAPI()

# ----------------------------------------------------------------------------------------

class DatabasesView(View):

	template_name = 'databases/list.html'

	def get(self, request, page=1, *args, **kwargs):

		q = request.GET.get('q', '').strip()

		if q:

			data = database_api.search(query=re.sub(r'\s+', '+', q), page=page)
			
		else:

			data = database_api.database_list(page=page, per_page=20)


		print(data)
			

		context = { 

			'databases': data.get('databases'), 
			'meta': data.get('meta'),
			'message': data.get('error_message'),
			'q': q

		}

		if request.is_ajax():

			return JsonResponse(context, status=200 if context['message'] == None else 403)

		return render(request, self.template_name, context)

# ----------------------------------------------------------------------------------------

class DownloadDatabaseView(View):

	def get(self, request, database_code, *args, **kwargs):

		data = database_api.download(database_code)
		
		context = { 'message': data.get('error_message', '%s downloaded.' %(database_code)) }


		if request.is_ajax():

			return JsonResponse(context, status=200)

		else:

			return redirect('databases:list')


# ----------------------------------------------------------------------------------------

stockbot/datasets/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals
import re

# Core django imports
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View

# Thrid party app imports

# Project imports
from stockbot.quandl_api import DatabaseAPI, DatasetAPI

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

database_api = DatabaseAPI()
dataset_api = DatasetAPI()

# ----------------------------------------------------------------------------------------

class DatasetsView(View):

	template_name = 'datasets/list.html'

	def get(self, request, page=1, *args, **kwargs):
		
		context = {  }

		return render(request, self.template_name, context)

# ----------------------------------------------------------------------------------------

stockbot/stocks/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.views.generic import View

# Thrid party app imports

# Project imports
from stockbot.quandl_api import DatabaseAPI, DatatableAPI, DatasetAPI

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

database_api = DatabaseAPI()
datatable_api = DatatableAPI()
dataset_api = DatasetAPI()

# ----------------------------------------------------------------------------------------

class IndexView(View):

	template_name = 'stocks/index.html'


	def get(self, request, *args, **kwargs):
		
		#print( database_api.database_list(page=10) )

		return render(request, self.template_name, {})

# ----------------------------------------------------------------------------------------

stockbot/templates/base.html
{# base html template #}
{% load staticfiles i18n %}

<!DOCTYPE html>

<html lang="en">

  <head>

    <!-- Meta ======================================================================== -->

    <meta charset="utf-8">

    <meta http-equiv="x-ua-compatible" content="IE=edge">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Used by search engines -->
    <meta name="description" content="Quandl API">

    <!-- Search keywords -->
    <meta name="keywords" content="quandl, api">
    
    <!-- Indicates if the search engine should add this page to their results -->
    <meta name="robots" content="follow">
    
    <meta name="author" content="TA">

    <!-- Page specific Meta. Each tag must be given the class "meta_tag" -->
    {% block meta %}{% endblock meta %}

    <!-- END Meta ==================================================================== -->


    <!-- Page Title ================================================================== -->
    
    <title>{% block title %}{{ site_name }}{% endblock title %}</title>

    <!-- END Page Title ============================================================== -->

    
    <!-- CSS ========================================================================= -->

    <!-- Site wide CSS -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">

    <!-- Page specific CSS. Each link must be given the class "css_file" -->
    {% block css %}{% endblock css %}
    
    <!-- END CSS ===================================================================== -->

  </head>




  <body>

    <!-- navigation ================================================================== -->

    <header role="banner">
        
        <nav class="nav_bar container" role="navigation">
            
            <ul id="nav_ul">

                <li>
                    
                    <a href="{% url 'index' %}" title="Quandl API">Quandl API</a>

                </li><li>
                    
                    <a href="{% url 'databases:list' %}" title="Databases">Databases</a>

                </li><li>
                    
                    <a href="{% url 'datasets:list' %}" title="Datasets">Datasets</a>

                </li>
            
            </ul>

        </nav>

    </header>

    <!-- END navigation ============================================================== -->

    


    <!-- Main Content ================================================================ -->
    
    <div id="content_container">

        <!-- messages ==================================================================== -->

        <div id="messages" class="box_border{% if message %} show no_js"{% endif %}">

            <div class="wrapper">

                <div class="container box_border">
                     
                    <div class="text"> 

                        {% if message %}
                        <p>{{ message }}</p>
                        {% endif %}
                    
                    </div>

                </div>

            </div>
            
        </div>

        <!-- end messages ================================================================ -->

        <main role="main" id="main_content" class="container box_border">

            {% block content %}{% endblock content %}
            
        </main>

    </div>

    <!-- END Main Content ============================================================ -->
    



    <!-- Javascript ================================================================== -->
    
    {% block base_js %}
    
    <!-- Site wide Javascript files -->
    <script src="{% static 'js/libraries/jquery-1.12.2.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    
    {% endblock base_js %}

    <!-- Page specific Javascript files. Each file must be given the class "js_file" -->
    {% block js %}{% endblock js %}

    <!-- END Javascript ============================================================== -->

  </body>

</html>

stockbot/templates/databases/list.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Databases{% endblock title %}


{% block css %}<link href="{% static 'css/databases/list.css' %}" rel="stylesheet" type="text/css">{% endblock css %}


{% block content %}
<div id="databases_list_view">

	<div id="title">

		<h1>Databases</h1>
		{% if meta %}
		<small>page <span id="page_number">{{meta.current_page}}</span> of {{meta.total_pages}}</small>
		{% endif %}
	
	</div>

	<div>

	<form actions="{% url 'databases:list' %}" method="get">

		<input class="text box_border" type="text" name="q" value="{{q}}">
		<input class="submit box_border" type="submit" name="submit" value="Search">

	</form>

	</div>

	<table id="databases">

		<tr class="columns">
			<th>Name</th>
			<th>Code</th>
			<th>Description</th>
			<th>Premium</th>
			<th>Download</th>
		</tr>

		{% for database in databases %}
		<tr class="row">
			<td class="name">{{ database.name }}</td>
			<td class="database_code">{{ database.database_code }}</td>
			<td class="description">{{ database.description }}</td>
			<td class="premium">{{ database.premium }}</td>
			<td class="download"><a href="{% url 'databases:download' database.database_code %}" class="download_db">Download</a></td>
		</tr>
		{% empty %}
		<tr class="row">
			<td class="empty">No databases found.</td>
			<td class="spacing"></td>
			<td class="spacing"></td>
			<td class="spacing"></td>
		</tr>
		{% endfor%}

	</table>

	{% if meta and meta.current_page < meta.total_pages %}
	<div id="load_databases">
		<a href="{% url 'databases:list' meta.next_page %}">Load databases</a>
	</div>
	{% endif %}

</div>
{% endblock content %}


{% block js %}<script src="{% static 'js/databases/list.js' %}"></script>{% endblock js %}

stockbot/templates/datasets/list.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Datasets{% endblock title %}


{% block css %}<link href="{% static 'css/datasets/list.css' %}" rel="stylesheet" type="text/css">{% endblock css %}


{% block content %}
<div id="datasets_list_view">

	<div id="title">

		<h1>Datasets</h1>
		{% if meta %}
		<small>page <span id="page_number">{{meta.current_page}}</span> of {{meta.total_pages}}</small>
		{% endif %}
	
	</div>

	<div>

	<form actions="{% url 'datasets:list' %}" method="get">

		<input class="text box_border" type="text" name="q" value="{{q}}">
		<input class="submit box_border" type="submit" name="submit" value="Search">

	</form>

	</div>

	<table id="datasets">

		<tr class="columns">
			<th>Name</th>
			<th>Code</th>
			<th>Description</th>
			<th>Premium</th>
		</tr>

		{% for dataset in datasets %}
		<tr class="row">
			<td class="name">{{ dataset.name }}</td>
			<td class="database_code">{{ dataset.database_code }}</td>
			<td class="description">{{ dataset.description }}</td>
			<td class="premium">{{ dataset.premium }}</td>
		</tr>
		{% empty %}
		<tr class="row">
			<td class="empty">No datasets found.</td>
			<td class="spacing"></td>
			<td class="spacing"></td>
			<td class="spacing"></td>
		</tr>
		{% endfor%}

	</table>

	{% if meta and meta.current_page < meta.total_pages %}
	<div id="load_databases">
		<a href="{% url 'datasets:list' meta.next_page %}">Load datasets</a>
	</div>
	{% endif %}

</div>
{% endblock content %}


{% block js %}<script src="{% static 'js/datasets/list.js' %}"></script>{% endblock js %}

stockbot/templates/stocks/index.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}{{ site_name }}{% endblock title %}


{% block css %}{% endblock css %}


{% block content %}
<div>

	<h1>Quandl API</h1>

</div>
{% endblock content %}


{% block js %}{% endblock js %}